#!/bin/bash

# Remove old build folder
rm -rf build

# Create a clean build folder
mkdir build
cd build

# Generate build files with CMake
cmake ..

# Build using all CPU cores
make -j$(nproc)

# Run the executable
./AudioPlaylistManager

